import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import {
  adminConfigState,
  type AdminConfigState,
  type AdminFieldConfig,
  type AdminRuleConfig,
  type AdminTabConfig,
} from "@/lib/schema";

const defaultTabs: AdminTabConfig[] = [
  {
    tabKey: "oemChassis",
    label: "OEM Chassis",
    sortOrder: 1,
    isHidden: false,
  },
  {
    tabKey: "bodyUi",
    label: "Body UI",
    sortOrder: 2,
    isHidden: false,
  },
];

const defaultFields: AdminFieldConfig[] = [
  {
    fieldKey: "make",
    tabKey: "oemChassis",
    label: "Make",
    type: "select",
    placeholder: "Select Make",
    sortOrder: 1,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "Volvo", label: "Volvo", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "Scania", label: "Scania", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
      { value: "MAN", label: "MAN", price: 0, isDisplayPrice: false, sortOrder: 3, isHidden: false },
      { value: "Daimler", label: "Daimler", price: 0, isDisplayPrice: false, sortOrder: 4, isHidden: false },
      { value: "Renault", label: "Renault", price: 0, isDisplayPrice: false, sortOrder: 5, isHidden: false },
    ],
  },
  {
    fieldKey: "modelYear",
    tabKey: "oemChassis",
    label: "Model Year",
    type: "select",
    placeholder: "Select Year",
    sortOrder: 2,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "2024", label: "2024", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "2023", label: "2023", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
      { value: "2022", label: "2022", price: 0, isDisplayPrice: false, sortOrder: 3, isHidden: false },
      { value: "2021", label: "2021", price: 0, isDisplayPrice: false, sortOrder: 4, isHidden: false },
      { value: "2020", label: "2020", price: 0, isDisplayPrice: false, sortOrder: 5, isHidden: false },
    ],
  },
  {
    fieldKey: "cabStyle",
    tabKey: "oemChassis",
    label: "Cab Style",
    type: "select",
    placeholder: "Select Cab Style",
    sortOrder: 3,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "Day Cab", label: "Day Cab", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "Sleeper Cab", label: "Sleeper Cab", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
      { value: "Crew Cab", label: "Crew Cab", price: 0, isDisplayPrice: false, sortOrder: 3, isHidden: false },
    ],
  },
  {
    fieldKey: "modelName",
    tabKey: "oemChassis",
    label: "Model Name",
    type: "select",
    placeholder: "Select Model",
    sortOrder: 4,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "FH16", label: "FH16", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "S730", label: "S730", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
      { value: "TGX", label: "TGX", price: 0, isDisplayPrice: false, sortOrder: 3, isHidden: false },
      { value: "Actros", label: "Actros", price: 0, isDisplayPrice: false, sortOrder: 4, isHidden: false },
      { value: "T", label: "T", price: 0, isDisplayPrice: false, sortOrder: 5, isHidden: false },
    ],
  },
  {
    fieldKey: "cabType",
    tabKey: "oemChassis",
    label: "Cab Type",
    type: "select",
    placeholder: "Select Cab Type",
    sortOrder: 5,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "Standard", label: "Standard", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "Premium", label: "Premium", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
      { value: "Executive", label: "Executive", price: 0, isDisplayPrice: false, sortOrder: 3, isHidden: false },
    ],
  },
  {
    fieldKey: "ca",
    tabKey: "oemChassis",
    label: "CA",
    type: "select",
    placeholder: "Select CA",
    sortOrder: 6,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "2.5m", label: "2.5m", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "3.0m", label: "3.0m", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
      { value: "3.5m", label: "3.5m", price: 0, isDisplayPrice: false, sortOrder: 3, isHidden: false },
      { value: "4.0m", label: "4.0m", price: 0, isDisplayPrice: false, sortOrder: 4, isHidden: false },
    ],
  },
  {
    fieldKey: "wb",
    tabKey: "oemChassis",
    label: "WB",
    type: "select",
    placeholder: "Select WB",
    sortOrder: 7,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "3.0m", label: "3.0m", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "3.5m", label: "3.5m", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
      { value: "4.0m", label: "4.0m", price: 0, isDisplayPrice: false, sortOrder: 3, isHidden: false },
      { value: "4.5m", label: "4.5m", price: 0, isDisplayPrice: false, sortOrder: 4, isHidden: false },
      { value: "5.0m", label: "5.0m", price: 0, isDisplayPrice: false, sortOrder: 5, isHidden: false },
    ],
  },
  {
    fieldKey: "fuelType",
    tabKey: "oemChassis",
    label: "Fuel Type",
    type: "select",
    placeholder: "Select Fuel Type",
    sortOrder: 8,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "Diesel", label: "Diesel", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "LNG", label: "LNG", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
      { value: "Hybrid", label: "Hybrid", price: 0, isDisplayPrice: false, sortOrder: 3, isHidden: false },
      { value: "Electric", label: "Electric", price: 0, isDisplayPrice: false, sortOrder: 4, isHidden: false },
    ],
  },
  {
    fieldKey: "gvwr",
    tabKey: "oemChassis",
    label: "GVWR",
    type: "select",
    placeholder: "Select GVWR",
    sortOrder: 9,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "33,000", label: "33,000", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "52,000", label: "52,000", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
      { value: "66,000", label: "66,000", price: 0, isDisplayPrice: false, sortOrder: 3, isHidden: false },
      { value: "80,000", label: "80,000", price: 0, isDisplayPrice: false, sortOrder: 4, isHidden: false },
    ],
  },
  {
    fieldKey: "rearWheelDriveType",
    tabKey: "oemChassis",
    label: "Rear Wheel Drive Type",
    type: "select",
    placeholder: "Select Drive Type",
    sortOrder: 10,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "Single", label: "Single", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "Dual", label: "Dual", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
      { value: "Tridem", label: "Tridem", price: 0, isDisplayPrice: false, sortOrder: 3, isHidden: false },
    ],
  },
  {
    fieldKey: "bodyType",
    tabKey: "bodyUi",
    label: "Body Type",
    type: "select",
    placeholder: "Select Body Type",
    sortOrder: 1,
    isRequired: true,
    isHidden: false,
    isDisplayPrice: false,
    basePrice: 0,
    options: [
      { value: "dump", label: "Dump Body", modelFileName: "dump_body.glb", price: 0, isDisplayPrice: false, sortOrder: 1, isHidden: false },
      { value: "service", label: "Service Body", modelFileName: "service_body.glb", price: 0, isDisplayPrice: false, sortOrder: 2, isHidden: false },
    ],
  },
  {
    fieldKey: "dump_length",
    tabKey: "bodyUi",
    label: "Length",
    type: "select",
    placeholder: "Select Length",
    sortOrder: 2,
    isRequired: true,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "dump" }],
    options: [
      { value: "336", label: "336", price: 47740, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "360", label: "360", price: 51715, isDisplayPrice: true, sortOrder: 2, isHidden: false },
      { value: "384", label: "384", price: 55690, isDisplayPrice: true, sortOrder: 3, isHidden: false },
      { value: "192", label: "192", price: 47740, isDisplayPrice: true, sortOrder: 4, isHidden: false },
      { value: "216", label: "216", price: 47740, isDisplayPrice: true, sortOrder: 5, isHidden: false },
    ],
  },
  {
    fieldKey: "dump_sideHeight",
    tabKey: "bodyUi",
    label: "Side Height",
    type: "select",
    placeholder: "Select Side Height",
    sortOrder: 3,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "dump" }],
    options: [
      { value: "57", label: "57", price: 0, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "60", label: "60", price: 800, isDisplayPrice: true, sortOrder: 2, isHidden: false },
      { value: "63", label: "63", price: 1600, isDisplayPrice: true, sortOrder: 3, isHidden: false },
    ],
  },
  {
    fieldKey: "dump_bodyStyle",
    tabKey: "bodyUi",
    label: "Body Style",
    type: "select",
    placeholder: "Select Body Style",
    sortOrder: 4,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "dump" }],
    options: [
      { value: "Square", label: "Square", price: 0, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "Tapered", label: "Tapered", price: 400, isDisplayPrice: true, sortOrder: 2, isHidden: false },
      { value: "Elliptical", label: "Elliptical", price: 600, isDisplayPrice: true, sortOrder: 3, isHidden: false },
    ],
  },
  {
    fieldKey: "dump_rearGate",
    tabKey: "bodyUi",
    label: "Rear Gate",
    type: "select",
    placeholder: "Select Rear Gate",
    sortOrder: 5,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "dump" }],
    options: [
      { value: "Cargo Door", label: "Cargo Door", price: 0, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "Lift Door", label: "Lift Door", price: 1200, isDisplayPrice: true, sortOrder: 2, isHidden: false },
    ],
  },
  {
    fieldKey: "dump_asphaltGate",
    tabKey: "bodyUi",
    label: "Asphalt Gate",
    type: "select",
    placeholder: "Select Asphalt Gate",
    sortOrder: 6,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "dump" }],
    options: [
      { value: "No", label: "No", price: 0, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "1", label: "1", price: 100, isDisplayPrice: true, sortOrder: 2, isHidden: false },
      { value: "2", label: "2", price: 175, isDisplayPrice: true, sortOrder: 3, isHidden: false },
      { value: "3", label: "3", price: 250, isDisplayPrice: true, sortOrder: 4, isHidden: false },
    ],
  },
  {
    fieldKey: "dump_tailgateAngle",
    tabKey: "bodyUi",
    label: "Tailgate Angle",
    type: "select",
    placeholder: "Select Tailgate Angle",
    sortOrder: 7,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "dump" }],
    options: [
      { value: "90°", label: "90°", price: 0, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "20°", label: "20°", price: 125, isDisplayPrice: true, sortOrder: 2, isHidden: false },
    ],
  },
  {
    fieldKey: "dump_hoist",
    tabKey: "bodyUi",
    label: "Hoist",
    type: "select",
    placeholder: "Select Hoist",
    sortOrder: 8,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "dump" }],
    options: [
      { value: "Power Up", label: "Power Up", price: 0, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "Power Up & Down", label: "Power Up & Down", price: 750, isDisplayPrice: true, sortOrder: 2, isHidden: false },
    ],
  },
  {
    fieldKey: "dump_cabGuard",
    tabKey: "bodyUi",
    label: "Cab Guard",
    type: "select",
    placeholder: "Select Cab Guard",
    sortOrder: 9,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "dump" }],
    options: [
      { value: "Yes", label: "Yes", price: 780, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "No", label: "No", price: 0, isDisplayPrice: true, sortOrder: 2, isHidden: false },
    ],
  },
  {
    fieldKey: "service_length",
    tabKey: "bodyUi",
    label: "Length",
    type: "select",
    placeholder: "Select Length",
    sortOrder: 10,
    isRequired: true,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "service" }],
    options: [
      { value: "82", label: "82", price: 10965, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "97", label: "97", price: 11560, isDisplayPrice: true, sortOrder: 2, isHidden: false },
      { value: "108", label: "108", price: 12980, isDisplayPrice: true, sortOrder: 3, isHidden: false },
      { value: "130", label: "130", price: 14590, isDisplayPrice: true, sortOrder: 4, isHidden: false },
      { value: "134", label: "134", price: 15280, isDisplayPrice: true, sortOrder: 5, isHidden: false },
    ],
  },
  {
    fieldKey: "service_width",
    tabKey: "bodyUi",
    label: "Width",
    type: "select",
    placeholder: "Select Width",
    sortOrder: 11,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "service" }],
    options: [
      { value: "78", label: "78", price: 0, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "80", label: "80", price: 350, isDisplayPrice: true, sortOrder: 2, isHidden: false },
      { value: "82", label: "82", price: 550, isDisplayPrice: true, sortOrder: 3, isHidden: false },
      { value: "94", label: "94", price: 965, isDisplayPrice: true, sortOrder: 4, isHidden: false },
    ],
  },
  {
    fieldKey: "service_height",
    tabKey: "bodyUi",
    label: "Height",
    type: "select",
    placeholder: "Select Height",
    sortOrder: 12,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "service" }],
    options: [
      { value: "36", label: "36", price: 0, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "40", label: "40", price: 125, isDisplayPrice: true, sortOrder: 2, isHidden: false },
      { value: "43", label: "43", price: 185, isDisplayPrice: true, sortOrder: 3, isHidden: false },
      { value: "46", label: "46", price: 235, isDisplayPrice: true, sortOrder: 4, isHidden: false },
      { value: "60", label: "60", price: 400, isDisplayPrice: true, sortOrder: 5, isHidden: false },
    ],
  },
  {
    fieldKey: "service_ca",
    tabKey: "bodyUi",
    label: "CA",
    type: "select",
    placeholder: "Select CA",
    sortOrder: 13,
    isRequired: false,
    isHidden: false,
    isDisplayPrice: true,
    basePrice: 0,
    visibleWhen: [{ fieldKey: "bodyType", operator: "eq", value: "service" }],
    options: [
      { value: "40", label: "40", price: 0, isDisplayPrice: true, sortOrder: 1, isHidden: false },
      { value: "56", label: "56", price: 40, isDisplayPrice: true, sortOrder: 2, isHidden: false },
      { value: "60", label: "60", price: 90, isDisplayPrice: true, sortOrder: 3, isHidden: false },
      { value: "82", label: "82", price: 140, isDisplayPrice: true, sortOrder: 4, isHidden: false },
      { value: "84", label: "84", price: 160, isDisplayPrice: true, sortOrder: 5, isHidden: false },
    ],
  },
];

const defaultRules: AdminRuleConfig[] = [
  {
    ruleKey: "dump_sideHeight_default_by_length",
    ruleType: "defaultByParentSelection",
    parentFieldKey: "dump_length",
    targetFieldKey: "dump_sideHeight",
    mapping: {
      "192": "57",
      "216": "57",
      "336": "57",
      "360": "60",
      "384": "63",
    },
    stopIfManualOverride: true,
    isHidden: false,
  },
  {
    ruleKey: "dump_bodyStyle_default_by_length",
    ruleType: "defaultByParentSelection",
    parentFieldKey: "dump_length",
    targetFieldKey: "dump_bodyStyle",
    mapping: {
      "192": "Square",
      "216": "Square",
      "336": "Square",
      "360": "Tapered",
      "384": "Elliptical",
    },
    stopIfManualOverride: true,
    isHidden: false,
  },
  {
    ruleKey: "dump_rearGate_default_by_length",
    ruleType: "defaultByParentSelection",
    parentFieldKey: "dump_length",
    targetFieldKey: "dump_rearGate",
    mapping: {
      "192": "Cargo Door",
      "216": "Cargo Door",
      "336": "Cargo Door",
      "360": "Cargo Door",
      "384": "Lift Door",
    },
    stopIfManualOverride: true,
    isHidden: false,
  },
  {
    ruleKey: "dump_asphaltGate_default_by_length",
    ruleType: "defaultByParentSelection",
    parentFieldKey: "dump_length",
    targetFieldKey: "dump_asphaltGate",
    mapping: {
      "192": "No",
      "216": "No",
      "336": "No",
      "360": "1",
      "384": "2",
    },
    stopIfManualOverride: true,
    isHidden: false,
  },
  {
    ruleKey: "dump_tailgateAngle_default_by_length",
    ruleType: "defaultByParentSelection",
    parentFieldKey: "dump_length",
    targetFieldKey: "dump_tailgateAngle",
    mapping: {
      "192": "90°",
      "216": "90°",
      "336": "90°",
      "360": "20°",
      "384": "20°",
    },
    stopIfManualOverride: true,
    isHidden: false,
  },
  {
    ruleKey: "dump_hoist_default_by_length",
    ruleType: "defaultByParentSelection",
    parentFieldKey: "dump_length",
    targetFieldKey: "dump_hoist",
    mapping: {
      "192": "Power Up",
      "216": "Power Up",
      "336": "Power Up",
      "360": "Power Up & Down",
      "384": "Power Up & Down",
    },
    stopIfManualOverride: true,
    isHidden: false,
  },
  {
    ruleKey: "dump_cabGuard_default_by_length",
    ruleType: "defaultByParentSelection",
    parentFieldKey: "dump_length",
    targetFieldKey: "dump_cabGuard",
    mapping: {
      "192": "Yes",
      "216": "Yes",
      "336": "Yes",
      "360": "No",
      "384": "No",
    },
    stopIfManualOverride: true,
    isHidden: false,
  },
  {
    ruleKey: "service_width_default_by_length",
    ruleType: "defaultByParentSelection",
    parentFieldKey: "service_length",
    targetFieldKey: "service_width",
    mapping: {
      "82": "78",
      "97": "80",
      "108": "94",
      "130": "82",
      "134": "78",
    },
    stopIfManualOverride: true,
    isHidden: false,
  },
  {
    ruleKey: "service_height_default_by_length",
    ruleType: "defaultByParentSelection",
    parentFieldKey: "service_length",
    targetFieldKey: "service_height",
    mapping: {
      "82": "36",
      "97": "40",
      "108": "43",
      "130": "46",
      "134": "60",
    },
    stopIfManualOverride: true,
    isHidden: false,
  },
  {
    ruleKey: "service_ca_default_by_length",
    ruleType: "defaultByParentSelection",
    parentFieldKey: "service_length",
    targetFieldKey: "service_ca",
    mapping: {
      "82": "40",
      "97": "56",
      "108": "60",
      "130": "82",
      "134": "84",
    },
    stopIfManualOverride: true,
    isHidden: false,
  },
];

type AdminConfigUpdateInput = {
  tabsJson: AdminTabConfig[];
  fieldsJson: AdminFieldConfig[];
  rulesJson: AdminRuleConfig[];
  updatedBy?: string | null;
};

export const createDefaultAdminConfig = () => ({
  id: 1 as const,
  configName: "trailer-configurator",
  schemaVersion: 1,
  tabsJson: defaultTabs,
  fieldsJson: defaultFields,
  rulesJson: defaultRules,
  isActive: true,
  updatedBy: "system",
  updatedAt: new Date(),
});

export async function getOrCreateAdminConfig(): Promise<AdminConfigState> {
  const existing = await db.query.adminConfigState.findFirst({
    where: eq(adminConfigState.id, 1),
  });

  if (existing) {
    return existing;
  }

  const [created] = await db
    .insert(adminConfigState)
    .values(createDefaultAdminConfig())
    .returning();

  return created;
}

export async function updateAdminConfig(
  input: AdminConfigUpdateInput
): Promise<AdminConfigState> {
  const current = await getOrCreateAdminConfig();

  const [updated] = await db
    .update(adminConfigState)
    .set({
      tabsJson: input.tabsJson,
      fieldsJson: input.fieldsJson,
      rulesJson: input.rulesJson,
      updatedBy: input.updatedBy ?? current.updatedBy,
      updatedAt: new Date(),
      schemaVersion: current.schemaVersion + 1,
    })
    .where(eq(adminConfigState.id, 1))
    .returning();

  return updated;
}